from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("MCP Tools")


@mcp.tool()
def initialize_mcp_project(project_name: str = "new-mcp-server") -> str:
    """
    Initialize a new MCP server project with uv virtual environment and required structure.
    Returns setup instructions and project structure details.
    
    Args:
        project_name: Name of the MCP project to create (default: "new-mcp-server")
    """
    return f"""# Initialize MCP Server Project: {project_name}

Please create a new Model Context Protocol (MCP) server project with the following setup:

## Project Structure
```
{project_name}/
├── src/
│   ├── __init__.py
│   ├── server.py          # FastMCP server implementation
│   └── handlers/
│       └── __init__.py
├── tests/
│   ├── __init__.py
│   └── test_server.py
├── pyproject.toml          # Project metadata and dependencies
├── uv.lock                 # Lockfile (generated by uv)
└── README.md
```

## Setup Steps

1. **Create the project directory:**
   ```bash
   mkdir {project_name}
   cd {project_name}
   ```

2. **Initialize uv project:**
   ```bash
   uv init
   ```

3. **Create virtual environment:**
   ```bash
   uv venv
   ```

4. **Add FastMCP dependency:**
   ```bash
   uv add "mcp[cli]"
   ```
   
   Note: `uv add` automatically uses the virtual environment, so activation is not required for this step.

5. **Create the basic server structure:**
   - Create src/server.py with FastMCP initialization
   - Set up handlers directory for tools/prompts/resources
   - Add tests directory

Note: Environment activation is not needed when using `uv run` commands, as `uv` automatically manages the virtual environment.

## Basic server.py Template

```python
from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("{project_name}")

@mcp.tool()
def example_tool(input: str) -> str:
    \"\"\"Example tool that echoes input\"\"\"
    return f"Echo: {{input}}"

if __name__ == "__main__":
    mcp.run()
```

## Testing with MCP Inspector

Test your server with the MCP Inspector:

```bash
uv run mcp dev src/server.py
```

This will open the MCP Inspector in your browser where you can:
- Test your tools interactively
- View server logs in real-time
- Debug issues before deploying to a client

**Note:** Use `uv run` to automatically access the `mcp` CLI tool from your project dependencies.

## Running the Server in Production

**Important:** The MCP server runs as a persistent process and will appear to "hang" in the console. This is normal behavior - the server is running and waiting for connections from an MCP client (like Claude Desktop, Cline, or other LLM tools).

**For client configuration:**
```bash
uv run python src/server.py
# Server will start and wait for connections
# Press Ctrl+C to stop
```

## Next Steps

1. Test your server with `uv run mcp dev src/server.py` in the inspector
2. Add the server to your MCP client configuration (e.g., Claude Desktop config)
3. The client will handle starting/stopping the server automatically

Please proceed with creating this project structure, setting up the uv virtual environment, and creating all necessary files.
"""


@mcp.tool()
def mcp_project_best_practices() -> str:
    """
    Retrieve best practices and guidelines for developing MCP servers.
    """
    return """# MCP Server Development Best Practices

## Project Organization

1. **Separate concerns:**
   - Keep server initialization in server.py
   - Put tools/prompts/resources in handlers/
   - Use clear, descriptive names for your functions

2. **Use type hints:**
   - FastMCP relies on type hints for schema generation
   - Always annotate parameters and return types

3. **Write good docstrings:**
   - The docstring becomes the tool/prompt description
   - Be clear and concise about what it does
   - Document parameters with Args: section

## Dependency Management with uv

1. **Use uv for fast, reliable dependency management:**
   ```bash
   uv add <package>      # Add a dependency
   uv remove <package>   # Remove a dependency
   uv sync               # Sync environment with lockfile
   ```

2. **Keep pyproject.toml clean and organized**

3. **Commit uv.lock for reproducible builds**

## Testing

1. **Write tests for your tools/prompts:**
   - Use pytest
   - Test edge cases and error handling
   - Mock external dependencies

2. **Run tests with uv:**
   ```bash
   uv run pytest
   ```

## FastMCP Decorators

- `@mcp.tool()` - For actions/operations
- `@mcp.prompt()` - For prompt templates
- `@mcp.resource()` - For data access

Choose the right decorator for your use case!
"""

if __name__ == "__main__":
    mcp.run()
